### ISSUE TITLE
Chunked messages

### ISSUE THREAD

**Issue by nf3xn** [Bavarder/Bavarder#13]
**Is your feature request related to a problem? Please describe.**
As a chatgpt user I am frustrated by openai message size limit when pasting code. It would be a good feature of your app.

**Describe the solution you'd like**
It would be better if any such messages were automagically chunked into a number of messages, with appropriate prompts to prevent them eliciting a response until the question is asked. The user should be warned that their message has been chunked and that additional prompts have been prepended as loading too much code at once affects the quality of the answers. 

**Describe alternatives you've considered**
There is no other way around the message size limit as it is governed by the api token limits. I usually have to do this manually.

**Comment by 0xMRTT** [comment]
This has been added only for OpenAI. Is there any others providers with which you experienced issues because of the prompt sice ?
