### ISSUE TITLE
GPT 3.5 Turbo forgets the API key

### ISSUE THREAD

**Issue by Mars7x** [Bavarder/Bavarder#14]
**Describe the bug**
The API key for GPT 3.5 Turbo is lost when you close the app.

**To Reproduce**
1. Select GPT 3.5 Turbo and enter an API key
2. Close the app
3. Open the app
4. The previously entered API key is gone

**Expected behavior**
Remember the API key.

**Desktop (please complete the following information):**
 - OS: Fedora 38

**Comment by 0xMRTT** [comment]
Currently the API key isn't saved. But soon, it'll be saved in the wallet

**Comment by 0xMRTT** [comment]
This has been fixed. This will appear in the next release
