### ISSUE TITLE
[Feature Request] Ability to select different fonts and select their custom size

### ISSUE THREAD

**Issue by abuturabofficial** [Bavarder/Bavarder#21]
**Is your feature request related to a problem? Please describe.**
Currently, the app looks very tiny even on the 1080p screen. It is difficult to read text.

**Describe the solution you'd like**
Maybe add the ability to select a custom font, as well as their custom sizes.

**Comment by 0xMRTT** [comment]
For the response or the prompt ?

**Comment by abuturabofficial** [comment]
> For the response or the prompt ?

I think, it would be great to have it for both.

**Comment by 0xMRTT** [comment]
Since the new version will feature a chat mode like in Fractal or in Paper Plane. I don't think it's necessary bc it'll not be looking tiny anymore
