### ISSUE TITLE
'Clear prompt after send' parameter doesn't work

### ISSUE THREAD

**Issue by rene-coty** [Bavarder/Bavarder#22]
**Describe the bug**
'Clear prompt after send' parameter doesn't erase the prompt

**To Reproduce**
1. Go to 'Preferences'
2. Click on ''Clear prompt after send'
3. Close 'Preferences'
4. Send a prompt and wait for an answer
5. Answer is received but prompt isn't cleared
6. Got to 'Preferences': the setting is back to initial state

**Expected behavior**
The sent prompt should be cleared and the settinf should have saved its modified state 

**Screenshots**
[Capture vidéo du 2023-05-08 09-51-34.webm](https://user-images.githubusercontent.com/95506494/236769721-1ae8c637-14d1-4da9-9ddd-f883f82dbce8.webm)

**Environement**

io.github.Bavarder.Bavarder 0.1.7
Environment: GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023
Providers: ['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo']

**Comment by 0xMRTT** [comment]
https://github.com/Bavarder/Bavarder/commit/142eefa310b557a74fb9d3c391c8f4fa4eee67b4 fixed that
