### ISSUE TITLE
AUR Package is broken.

### ISSUE THREAD

**Issue by nimafanniasl** [Bavarder/Bavarder#24]
**Describe the bug**
The AUR package is broken, the git version doesn't even install and the normal version installs with root permissions to run and no .desktop file.

**To Reproduce**
1. install bavarder with your favoraite AUR helper.
2. try to run it! there are no .desktop files so you can't run it from GUI, and from the terminal, you get this error: bash: /usr/bin/bavarder: Permission denied

**Expected behavior**
it should add a desktop file to apps and open without root permissions.

**Environment**
I opened the app from the terminal with sudo:

io.github.Bavarder.Bavarder 0.1.7
Environment: GNOME
Gtk: 4.10.3
Python: 3.11.3
OS: Linux 6.3.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:12 +0000
Providers: ['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo']

**Comment by 0xMRTT** [comment]
Yep I known. I'm going to fix that soon. If you want to fix it feel free to submit your pkgbuild

**Comment by nimafanniasl** [comment]
Thanks!

**Comment by 0xMRTT** [comment]
It should has been fixed

**Comment by nimafanniasl** [comment]
Yes, it is fixed, nice :)
