### ISSUE TITLE
Add a button to stop generating

### ISSUE THREAD

**Issue by Nokse22** [Bavarder/Bavarder#25]
## Problem
Hugging chat tends to give very lengthy answers, but there is no way to stop it and choose another model. The only way is to close the application.

## Possible solution
A button to stop receiving the answer.

If it is a problem because one could send too many requests you could block the user from sending other requests until the answer is finished, but let the user switch model to try again if he is not happy with the answer.

**Comment by 0xMRTT** [comment]
Update to 0.2.0 and you will have it :)
