### ISSUE TITLE
Text invisible in output

### ISSUE THREAD

**Issue by ramilrgk** [Bavarder/Bavarder#26]
**Describe the bug**
Unable to see output text after request. The output can be copied, but the text itself is invisible in the window. The problem occurs regardless of the providers
**To Reproduce**
1. Input question
2. Send question
3. No text in output window

**Expected behavior**
Visible text in output window

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/75021558/d0bef11a-437b-44bf-bd4a-38450a8d5617)

**Environement**
Please past the content of About > Troubleshooting > Debugging Information 

io.github.Bavarder.Bavarder 0.2.0
Environment: pop:GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A
Providers: ['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo', 'starcoder']

**Comment by ramilrgk** [comment]
The problem started after installing the latest app update. Everything was working fine before

**Comment by 0xMRTT** [comment]
Hmm, you can disable the new update by going to the preferences. (but that's a workaround and not a fix :) )

Can you run Bavarder from the CLI using `flatpak run io.github.Bavarder.Bavarder` and send me the output ?

**Comment by shadyslim2018** [comment]
Same problem here

flatpak run io.github.Bavarder.Bavarder

```
baichat
Setting selected provider to 0
Traceback (most recent call last):
  File "/app/share/bavarder/bavarder/main.py", line 995, in update_response
    theme_css = ":root {\n" + CUSTOM_STYLE.format(**variables) + " \n}\n" + css
KeyError: 'card_fg_color'
Traceback (most recent call last):
  File "/app/share/bavarder/bavarder/main.py", line 995, in update_response
    theme_css = ":root {\n" + CUSTOM_STYLE.format(**variables) + " \n}\n" + css
KeyError: 'card_fg_color'

```

**Comment by 0xMRTT** [comment]
Oh I understand why. Thanks for providing the output 

@shadyslim2018 Do you use any GTK Theme ? If yes could you send me the content of `~/.config/gtk-4.0/gtk.css`

**Comment by shadyslim2018** [comment]
```
@define-color accent_color #99c1f1;
@define-color accent_bg_color #3584e4;
```

**Comment by 0xMRTT** [comment]
Okay, this has been fixed in https://github.com/Bavarder/Bavarder/commit/15a73ae8d18b40c3570ed9a94f2a720a50902a3b
