### ISSUE TITLE
[Feature Request] Ability to resize the input and output boxes

### ISSUE THREAD

**Issue by OpenSauce04** [Bavarder/Bavarder#27]
**Is your feature request related to a problem? Please describe.**
My input is often significantly shorter than my output, usually just being a simple question. This leads to a large amount of dead space that could instead be taken up by displaying more output rather than having to scroll to read the rest of the response:
![image](https://github.com/Bavarder/Bavarder/assets/48618519/df85cf2e-68aa-4b32-97d2-90171d05b304)

**Describe the solution you'd like**
I'd suggest having the ability to click on the space between the input and output boxes and drag up and down to resize the boxes. This way, you can increase or decrease the size of the boxes when necessary. Here is a rough example showing what I mean:

![bavrs](https://github.com/Bavarder/Bavarder/assets/48618519/fb768ca6-5945-48c1-a061-305ece97cd0d)

**Comment by 0xMRTT** [comment]
![preview](https://github.com/Bavarder/Bavarder/assets/105598867/f991662f-4bca-4a12-bf27-fd3a9d6ce1da)
