### ISSUE TITLE
Unreadable answer with some gtk themes

### ISSUE THREAD

**Issue by jle64** [Bavarder/Bavarder#31]
**Describe the bug**
When using some color themes, the answer is not readable due to the background being the same color than the font.

**To Reproduce**

1. Have some color theming on your gtk, for example using [gradience](https://github.com/GradienceTeam/Gradience)
2. Type something and wait for answer to appear
3. You can't see anything

**Expected behavior**
You should be able to see the answer. The answer background should probably be the same than the question background.

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/7120882/5372522b-f4dd-4113-b82a-710253bfbf1c)

**Environement**
io.github.Bavarder.Bavarder 0.2.3
Environment: GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 6.2.15-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023
Providers: ['baichat', 'catgpt', 'hfopenassistantsft1pythia12b', 'openaigpt35turbo']
Use Theme: True
Use Text View: False
Clear After Send: False
Close All Without Dialog: False
Current Provider: hfopenassistantsft1pythia12b

**Comment by 0xMRTT** [comment]
Are you using Pretty Purple?

**Comment by jle64** [comment]
Yep.

**Comment by 0xMRTT** [comment]
Gonna check

**Comment by 0xMRTT** [comment]
![image](https://github.com/Bavarder/Bavarder/assets/105598867/816264ff-7523-49b2-8b55-d5cb580f3fd3)

Fixed theming, you will have to update your pretty purple theme and Bavarder (when there will be a new updat)

**Comment by jle64** [comment]
Thanks !
