### ISSUE TITLE
[Feature Request] Switch for choosing shortcut for sending prompt (Ctrl+Enter/Enter)

### ISSUE THREAD

**Issue by wsdmatty** [Bavarder/Bavarder#33]
**Is your feature request related to a problem? Please describe.**
When typing in a chat window, pressing enter on the keyboard usually sends the message. This saves on the time spent moving the hand from keyboard to mouse and back again to click the send button.

**Describe the solution you'd like**
When typing a prompt, hitting enter sends the prompt.

**Describe alternatives you've considered**
Moving the mouse and clicking the button is an option.

**Comment by 0xMRTT** [comment]
Nein! In Bavarder, you need to press Ctrl+enter to send the message because enter is for new line

**Comment by 0xMRTT** [comment]
Hmm, in that case! I'll find a way in the new Bavarder.

**Comment by 0xMRTT** [comment]
This will be the default in the next version
