### ISSUE TITLE
Answers from "Open-Assistant SFT-1 12B Model" provider are truncated

### ISSUE THREAD

**Issue by mossroy** [Bavarder/Bavarder#34]
**Describe the bug**
When you choose the "Open-Assistant SFT-1 12B Model", and ask a question, the answer is truncated at ~100 characters

**To Reproduce**
1. Select "Open-Assistant SFT-1 12B Model" or "Open-Assistant SFT-1 12B Model (HuggingChat)" provider
2. Type a question (that would expect a non-trivial answer)
3. See the answer is truncated

**Expected behavior**
Complete answer

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/890923/1c381f4c-e9ea-4654-9ad4-4865cbf3b2a4)
![image](https://github.com/Bavarder/Bavarder/assets/890923/36d12a8f-fcdc-4e0c-b0f4-de6ca92f830b)

**Environement**
io.github.Bavarder.Bavarder 0.2.3
Environment: ubuntu:GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023
Providers: ['baichat', 'hfopenassistantsft1pythia12b', 'openaigpt35turbo', 'huggingchat']
Use Theme: False
Use Text View: False
Clear After Send: False
Close All Without Dialog: False
Current Provider: hfopenassistantsft1pythia12b

**Additional context**
This issue does not appear with "BAI Chat" provider for example

**Comment by 0xMRTT** [comment]
That's beacause of the model .... I'm looking for an alternative

**Comment by 0xMRTT** [comment]
https://huggingface.co/facebook/blenderbot-400M-distill can be nice
