### ISSUE TITLE
The flatpak is out of date

### ISSUE THREAD

**Issue by fwsmit** [Bavarder/Bavarder#39]
The latest flatpak version is 0.2.3 as seen on https://flathub.org/apps/io.github.Bavarder.Bavarder

**Comment by 0xMRTT** [comment]
Bavarder is on going a full rewrite. It will be fixed soon

**Comment by PeterDaveHello** [comment]
As there's a `New version available!` prompt message at the top of the window, maybe v0.2.4 on Flatpak can be published first?

**Comment by 0xMRTT** [comment]
@PeterDaveHello 0.2.4 has been published but only for desktop ... I'm sorry about that and I prefer to release a full rewrite of Bavarder with a discussion mode and an improved support of local models

**Comment by PeterDaveHello** [comment]
@0xMRTT understood, just on flathub it seems to stuck on v0.2.3 two months ago, any chance that can be checked? Thanks!

**Comment by 0xMRTT** [comment]
@PeterDaveHello I'll fix it with v1.0.0

**Comment by PeterDaveHello** [comment]
It looks like v0.2.4 is on https://flathub.org/apps/io.github.Bavarder.Bavarder now.
