### ISSUE TITLE
Llama2 support

### ISSUE THREAD

**Issue by orvitpng** [Bavarder/Bavarder#41]
Llama2 is a new model developed by Microsoft and Facebook. The project could benefit from adding support for it. It wouldn't be hard because of the open and accessible nature of the model.

**Comment by 0xMRTT** [comment]
New Bavarder will have the ability to run gpt4all models which are based on llama.cpp

**Comment by orvitpng** [comment]
> New Bavarder will have the ability to run gpt4all models which are based on llama.cpp

Is this code already in the codebase? If not, I wouldn't consider this completed.

**Comment by 0xMRTT** [comment]
it's already in the codebase, you can even try it yourself by building the repo from source.
