### ISSUE TITLE
app stuck and acting weirdly on ChromeOS's Debian

### ISSUE THREAD

**Issue by Huge** [Bavarder/Bavarder#45]
- installed via `flatpak`
- with a free model it gets stuck with a wheel turning:
![Screenshot 2023-09-07 09 43 27](https://github.com/Bavarder/Bavarder/assets/111648/d74cc487-6261-42ef-a162-9b60177a8bbe)

- with API key provided for chat-gpt or GPT4 acts weird, no idea why:
![Screenshot 2023-09-07 09 43 46](https://github.com/Bavarder/Bavarder/assets/111648/e7d0dec8-09f1-46f8-847e-1ceb9e4a9666)

I am swearing a $2 donation if/when it gets fixed.

**Comment by 0xMRTT** [comment]
Hello, this will be fixed very soon. A new version will be released with a fix for that and with a new UI for GNOME 45

**Comment by 0xMRTT** [comment]
Yeah, this is because the old AI model stopped working... I'll replace it

**Comment by 0xMRTT** [comment]
1.0.0 will reach flathub soon

**Comment by Huge** [comment]
Just tested it, the interaction works now for the default model and for CatGPT, the API models seem to fail, although I get good responses from my CLI with the same API keys.-|
I will try to find some time to report that, for now I can share the message goes `You don't have access to this model, please check your plan and billing details.` and it most likely is not true, as I get completions/chat with the same keys elsewhere.

**Comment by 0xMRTT** [comment]
@Huge this seems to be a recurring issue... I'll investigate further
