### ISSUE TITLE
Uncomplete Answer for Long Answer Questions

### ISSUE THREAD

**Issue by NadjibC** [Bavarder/Bavarder#46]
The Program outputs only the first line of the Answer Text when the Answer consists of more than one line.

**To Reproduce**
Ask any question, which requires more than one line as an answer.

**Expected behavior**
Deduce a complete answer.

**Environment**
OS: Manjaro Linux
OS Version: 23.0.1 Uranos
Installed from Flatpak. io.github.Bavarder.Bavarder | Version: 0.2.4

**Used Provider**
Open-Assistant SF-1 12B Model

**Screenshots**
![Screenshot from 2023-09-11 14-27-24](https://github.com/Bavarder/Bavarder/assets/81011910/0bfb7e31-f547-4b44-b4fb-e18cf0bbbf18)

---

![Screenshot from 2023-09-11 14-29-13](https://github.com/Bavarder/Bavarder/assets/81011910/7739e5c6-22cb-4ca6-9ce2-5312840adc71)

**Terminal Output**
```
$ io.github.Bavarder.Bavarder                                                                                               [14:30:25]
Linux Torvalds is the founder and lead developer of the Linux kernel. He is also the founder
```

**Comment by 0xMRTT** [comment]
As soon as GNOME 45 will be released, Bavarder v1.0 will be released with a fix for that and a lot of features like an improved UI, a multi-chat mode (history), etc...

In the meantime, you can try switching provider or build Bavarder from source!
