### ISSUE TITLE
Open-Assistant SFT-112B responses are cut short

### ISSUE THREAD

**Issue by OpenSauce04** [Bavarder/Bavarder#48]
**Describe the bug**
Every response from Open-Assistant (the default provider option) is cut way too short for the response to be even slightly useful. It seems that sentences are being cut off mid-sentence

**To Reproduce**
1. Choose Open-Assistant as the provider
2. Attempt to ask a question

**Expected behavior**
The length of the answer should be long enough to allow the question to actually be answered

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/48618519/191c733a-5bbd-446b-a383-05b730709df3)
![image](https://github.com/Bavarder/Bavarder/assets/48618519/af2984f0-c51c-451f-acb0-014321d30ab7)

**Environment**
io.github.Bavarder.Bavarder 0.2.4
Environment: GNOME
Gtk: 4.10.5
Python: 3.10.13
OS: Linux 6.4.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.13-1 (2023-08-31)
Providers: ['baichat', 'catgpt', 'hfopenassistantsft1pythia12b', 'openaigpt35turbo']
Use Theme: False
Use Text View: False
Clear After Send: False
Close All Without Dialog: False
Current Provider: hfopenassistantsft1pythia12b

**Comment by 0xMRTT** [comment]
Bavarder 1.0 will fix it :)
