### ISSUE TITLE
Hangs when clicking on the 'Options' menu item.

### ISSUE THREAD

**Issue by Articmar** [Bavarder/Bavarder#50]
When I click on the 'Options' item, it hangs for a few seconds, after which the options dialog opens. Sometimes it offers to force close the application. 

[output.webm](https://github.com/Bavarder/Bavarder/assets/118318866/27d59e44-4647-487b-a1f3-d81052277fa4)

Bavarder v1.0.0 | Fedora Workstation 38 | GNOME 44.5 | Flatpak (GNOME Application Platform version 45)

_Also the 'Options' menu is duplicated, this item is in both the hamburger menu and the three dots menu, though maybe that's the way it's designed...._

**Comment by 0xMRTT** [comment]
#57 fixed that
