### ISSUE TITLE
All* providers generate short and/or generally unhelpful answers

### ISSUE THREAD

**Issue by OpenSauce04** [Bavarder/Bavarder#52]
\* I have not tested GPT 3.5 or GPT 4, as they require an API key. I have tested all other providers, as shown in the screenshots below

**Describe the bug**
Answers generated by providers are either very short, aren't relevant to the question, go on nonsense tangents, or all of the above

**To Reproduce**
1. Attempt to use the program's chat feature

**Expected behavior**
The responses should he helpful and relevant to the question

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/48618519/6bc65947-816f-4ff6-8a19-ef36ba81336c)
![image](https://github.com/Bavarder/Bavarder/assets/48618519/ae53aad7-e0f2-4d7e-be89-75e16f0c6566)
![image](https://github.com/Bavarder/Bavarder/assets/48618519/246492d7-8643-414f-b533-ce9b14564297)

**Environment**

io.github.Bavarder.Bavarder 1.0.0
Environment: GNOME
Gtk: 4.12.1
Python: 3.11.5
OS: Linux 6.5.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1 (2023-09-13)

**Comment by 0xMRTT** [comment]
You can try using a locally hosted provider by clicking on the cloud and downloading a model from the preferences. If you have any suggestions about online providers, tell me! 

PS: for ai horde you can switch the model from the preferences

**Comment by OpenSauce04** [comment]
AI Horde appears to not work at all

It just gets stuck endlessly generating a response

**Comment by OpenSauce04** [comment]
I've tried a myriad of models on AI Horde and every single one without fail has an issue where the response will get cut short mid-sentence or sometimes even mid-word

**Comment by 0xMRTT** [comment]
If you have any suggestions of a provider, I would be glad. Try to switch to another provider or host your own.
