### ISSUE TITLE
All GPT 3.5 Turbo and GPT 4 queries receive "You don't have access to this model, please check your plan and billing details."

### ISSUE THREAD

**Issue by LSeelig** [Bavarder/Bavarder#53]
**Describe the bug**
Whenever I send a query to one of these models (default URL) using my API key which works with other applications (https://github.com/kharvd/gpt-cli), I receive the message "You don't have access to this model, please check your plan and billing details."

**To Reproduce**
1. Upgrade to the OpenAI pay-as-you-go plan
2. Generate an API key
3. Enter it into "API key" field for GPT 3.5 Turbo and GPT 4 models
4. Switch chat to one of the two models
5. Make a query

**Expected behavior**
A response to the query

**Screenshots**
![image](https://github.com/Bavarder/Bavarder/assets/37001137/e5a9f1e2-007d-498b-a964-0c2f454a2d41)

**Environment**
Please post the content of About > Troubleshooting > Debugging Information 

io.github.Bavarder.Bavarder 1.0.0
Environment: GNOME
Gtk: 4.12.1
Python: 3.11.5
OS: Linux 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023

**Additional context**
When I last tried the app months ago with a different api key, I received a message that my quota had been exceeded whenever I made a prompt, even though the openai webpage said I barely used anything.

**Comment by 0xMRTT** [comment]
This is strange...

Can you try to run this in python and see if it's work ?

``` shell
pip install --upgrade openai # install the openai library from pypi
```

Now python:

``` py
import openai

openai.api_key = "sk-..."

completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])
print(completion.choices[0].message.content)
```

and tell me if you get the same error ?

**Comment by LSeelig** [comment]
No. Openai was previously installed by gpt-cli, but it had a version conflict. gpt-cli and reinstalled openai and ran the python script, I got "Hello! How can I assist you today?". I tried bavarder again (though the problem started before I installed gpt-cli), and it still didn't work.

**Comment by 0xMRTT** [comment]
I've only a little issue... it's that my free plan is over so I can't test it...

**Comment by CorvetteCole** [comment]
...shouldn't this not be a problem with the Flatpak since this should be bundled? (but it is)

**Comment by CorvetteCole** [comment]
Also, OpenAI's API pricing is pretty darn cheap if you stick to relatively low tokens with GPT3. You could do all the testing and keep your costs under $1/mo if you wanted. I'm sure the community would be willing to help with that

**Comment by 0xMRTT** [comment]
> Also, OpenAI's API pricing is pretty darn cheap if you stick to relatively low tokens with GPT3. You could do all the testing and keep your costs under $1/mo if you wanted. I'm sure the community would be willing to help with that

yeah you're right it can be possible

**Comment by m0nhawk** [comment]
@0xMRTT I have spent a little bit of time, because I was having the same error.

Though, after some investigation, [this](https://github.com/Bavarder/Bavarder/blob/2b2e7b6e916ee5a6441780771283c66400addfaf/src/providers/openai.py#L48) was not entirely correct, as `openai.error.InvalidRequestError` is quite broader than that error message.

After some debugging, the actual error (for me) was:
```
'User' is not one of ['system', 'assistant', 'user', 'function'] - 'messages.0.role'
````

Solving this is pretty straightforward, and I will be glad to help with this.

**Comment by 0xMRTT** [comment]
Thanks this is really helpful! I'll fix it soon

**Comment by SamuelBorn** [comment]
I am experiencing the same problem. I validated that my API key is working with this small program:

```
from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="ENTERED MY API KEY HERE",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-4",
)

print(chat_completion.choices[0].message.content)
```
But when I enter the GPT-4 key in Bavarder I get the same `"You don't have access to this model, please check your plan and billing details."` error.

Is it maybe because the stable flatpak is still using the old `openai.ChatCompletion.create` API?

**Comment by cmhobbs** [comment]
I'm also having this issue with both ChatGPT 3.5 and 4.  I have also validated my API key.

**Comment by CorvetteCole** [comment]
Yeah it is basically broken I'd just recommend using something else for now

**Comment by 0xMRTT** [comment]
#57 might have fixed this

**Comment by LSeelig** [comment]
> #57 might have fixed this

I have tried to build with the fix, but I keep getting pip errors. Even the referenced nightly build fails to launch.
