### ISSUE TITLE
Use OpenAI account for ChatGPT free

### ISSUE THREAD

**Issue by x80486** [Bavarder/Bavarder#55]
## Description

I have a free account in `OpenAI` for `ChatGPT`. Is it possible to use that account with the provided `ChatGPT` (free), but from within `Bavarder`?

The default free `Providers` in `Bavarder` really are not great, compared to the (free) `ChatGPT`.

## Describe Solution

To be able to use our credentials with the free `ChatGPT` provided by `OpenAI`.

## Describe Alternatives You've Considered

Login and use `ChatGPT` online :wink:

## Additional Context

N/A

**Comment by 0xMRTT** [comment]
It should be possible to use free credits...

**Comment by x80486** [comment]
Currently, I don't see a way to put my credentials (e-mail and password) in `Bavarder`, in the same way I do with the Web interface, like this:

![_Screenshot from 2023-10-16 12-59-33](https://github.com/Bavarder/Bavarder/assets/34633617/70098140-2bd4-4a03-ba7d-2583b1e0df23)

I can use the `GPT-3.5` option in the Web interface — but not `GPT-4`.

That's what I meant: using `GPT-3.5` with my credentials, but in the `Bavarder` desktop client. I'm not an avid user of `ChatGPT` (or these bots in general), so probably this doesn't make sense :grimacing:

**Comment by 0xMRTT** [comment]
You can't with your credentials but with your credentials you can generate an API key on OpenAI Platform which is used by Bavarder to access OpenAI API

**Comment by 0xMRTT** [comment]
It's related to #53
